test
ramiltanker/react-burger pull request #6
Opened 2021-07-15 09:19 UTC by ramiltanker

2021-07-20 09:40 UTC, AygulMalikova requested changes
Хорошая работа! У вас структурированный код, разделенный на компоненты, есть уместные комментарии.

Но есть небольшие замечания. В первую очередь прошу вас обратить внимание на нереализованный функционал, который указан в задании. Пожалуйста, используйте для названия коммитов и пул-реквестов соответствующие названия. И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/App/App.js
>    Router,
Надо исправить:

Названия коммитов и пул-реквеста должны соответствовать содержимому. Название `test` не отображается того, что содержится внутри них

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/SignIn/SignIn.js
Надо исправить:

Согласно заданию вам необходимо создать директорию pages. Внутри нее будут все страницы, которые описаны в задании и которые будут экспортироваться из одного файла index.js в директории pages

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/Profile/Profile.js
Надо исправить:

В пункте 5. Получение и обновление информации о пользователе задания указано, что у пользователя должна быть возможность обновить свои данные. На данный момент кнопки «Сохранить» и «Отмена» отсутствуют на вашей странице. Пожалуйста, добавьте кнопки и соответсвующий функционал

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/ResetPassword/ResetPassword.js
Надо исправить:

1. По условиям задания неавторизованный пользователь не может напрямую попасть на маршрут /reset-password. На данный момент есть возможность попасть на эту страницу (набрав адрес в адресной строке).
2. После ввода email на странице forgot-password и нажатии на кнопку "Восстановить" не происходит редиректа на страницу восстановления пароля. Также в консоли появляются ошибки, связанные с невалидным токеном

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/App/App.js
> +        <ProtectedRoute path="/profile/orders/:id">
Надо исправить:

Если пользователь нажимает на заказ, то на странице появляется ошибка: Failed to execute 'pushState' on 'History'

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/IngridientsIdPage/IngridientsIdPage.js
> +
Надо исправить:

Надо исправить:

Если обновить страницу с ингредиентом, то шапка профиля пропадает. Пожалуйста, исправьте, чтобы разметка страница соответствовала макету

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/App/App.js
>      <>
Надо исправить:
 
 Если пользователь переходит на несуществующий роут, то у него отображается пустая страница. Вам следует добавить, например, текст с сообщением о том, что данная страница не существует

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/App/App.js
>    withRouter,
Можно лучше:

Большая часть импортов не используется в данном файле. Пожалуйста, удалите их

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/App/App.js
>    React.useEffect(() => {
Надо исправить:

Если закрыть модальное окно с помощью ESC, то на странице появляется ошибка **Cannot read property 'stopPropagation' of undefined**. Пожалуйста, проверьте, что попап закрывается без ошибок

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/App/App.js
> +  let background =
Надо исправить:

Если значение переменной не перезаписывается напрямую, то следует использовать `const` вместо `let`

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/BurgerConstructor/BurgerConstructor.js
> -
Надо исправить:

На данный момент при попытке оформить заказ, текущий заказ обнуляется, но запрос на сервер не отправляется и модальное окно с заказом не отображается. Пожалуйста, исправьте это

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/BurgerConstructor/BurgerConstructor.js
> -      dispatch(sendOrder(ingridientsIds));
Можно лучше:

ingridients -> ingredients

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/BurgerConstructor/BurgerConstructor.js
>  const cardsInfoPropTypes = PropTypes.arrayOf(
Надо исправить:

Как вы можете заметить, тип ингредиента дублируется в нескольких компонентах. Представьте, что в один момент необходимо будет добавить/удалить/изменить одно поле, и тогда это придется делать в нескольких местах. Это нарушает принцип DRY (про него можно почитать в этой статье https://habr.com/ru/post/144611/). Вам следует вынести в отдельный тип, разместить его внутри utils и импортировать внутри компонентов, где он используется.

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/BurgerConstructor/BurgerConstructor.js
>  import ConstructorBurger from "../ConstructorBurgerCard/ConstructorBurgerCard.js";
Надо исправить:

Внутри компонента ConstructorBurgerCard на строке 85 `handleClose={props.сlose}` в close используется русская буква `c`

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/RouteBox/RouteBox.js
>    const isOrdersActive =
Можно лучше:

Вы можете упростить данное выражение: const isProfileActive = history.location.pathname === "/profile";

А также выражение ниже

2021-07-20 09:40 UTC, AygulMalikova commented on src/components/SignIn/SignIn.js
> +  console.log("in sign in");
Можно лучше:

Перед отправкой работы, пожалуйста, убедитесь в том, что все строки кода содержащие debugger и console.log удалены.

2021-07-20 09:40 UTC, AygulMalikova commented on src/services/actions/auth.js
> +export function handleCheckToken(refreshToken, nextFunc) {
Надо исправить:

Обратите внимание, что если пользователь не авторизирован, то проверка токена происходит постоянно (вы можете посмотреть на ошибки в консоли и во вкладке network). Этого не должно происходить.

2021-07-20 19:14 UTC, AygulMalikova commented
Очень хорошо! Вы исправили немало ошибок и движетесь в правильном направлении!
Осталось исправить ошибки с прошлой итерации:
- В пункте 5. Получение и обновление информации о пользователе задания указано, что у пользователя должна быть возможность обновить свои данные. На данный момент кнопки «Сохранить» и «Отмена» отсутствуют на вашей странице. Пожалуйста, добавьте кнопки и соответсвующий функционал
- Если пользователь переходит на несуществующий роут, то у него отображается пустая страница. Вам следует добавить, например, текст с сообщением о том, что данная страница не существует
- Если обновить страницу с ингредиентом, то шапка профиля пропадает. Пожалуйста, исправьте, чтобы разметка страница соответствовала макету

Также после восстановления пароля вам следует перенаправлять пользователя на главную страницу.

Удачи!

2021-07-22 09:42 UTC, AygulMalikova commented
Работа отклоняется без потери итерации, т.к. не все замечания с прошлой итерации были исправлены (404 и шапка страницы при обновлении страницы с ингредиентом). 

По поводу кнопок "Сохранить" и "Отмена" на страницы профиля. Функционал по сохранению работает, прошу прощения, что на прошлой итерации это не отметила. Однако кнопка "Отмена" работает не так как указано в задании. Ожидается: Нажатие кнопки «Отмена» на этой же странице возвращает информацию о пользователе к исходному значению до редактирования. Сейчас при нажатии на кнопку "Отмена" страница обновляется. Пожалуйста, исправьте это.

Желаю вам успехов!

2021-07-22 15:07 UTC, AygulMalikova commented
Ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать! Еще раз поздравляю и желаю вам дальнейших успехов!

2021-07-22 15:24 UTC, ramiltanker commented
Спасибо большое, вы отличный ревьювер. Спасибо вам !

2021-08-01 09:15 UTC, merged